---
- name: download jemalloc
  git: >
    repo="{{ jemalloc_git_repo }}"
    version="{{ jemalloc_version }}"
    dest="{{ jemalloc_src_path }}"
    force=yes
    depth=1

- name: autoconf jemalloc
  command: autoconf
  args:
    chdir: "{{ jemalloc_src_path }}"

- name: configure jemalloc
  command: ./configure
  args:
    chdir: "{{ jemalloc_src_path }}"

- name: make jemalloc
  command: make
  args:
    chdir: "{{ jemalloc_src_path }}"

- name: make install jemalloc
  command: make install
  args:
    chdir: "{{ jemalloc_src_path }}"
